on: push

name: Continuous integration cause why not

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: cargo-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ hashFiles('**/Cargo.toml') }}
            cargo-

      - name: Run tests
        run: |
          cd ${GITHUB_WORKSPACE}
          find . -name Cargo.toml | xargs -n1 cargo test --manifest-path

